/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. Open (no token) — the shell polls this (§4.4 step 2).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description SSE stream of typed `{type, payload}` envelopes: operation events from
         *     the runner, with heartbeats on idle.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shutdown
         * @description Respond 200, then exit cleanly (the drain runs in the app lifespan).
         */
        post: operations["shutdown_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Add-by-URL step 2 (US-JB-07) + programmatic ingest: persist one job with
         *     the same dedup/tombstone discipline as scan, then enqueue a score so the new
         *     row lands on the board with a fit rating.
         */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board
         * @description The paginated Job Board feed + header meta (FR-JB-02/10). Saved jobs are
         *     excluded server-side; Expired jobs stay (greyed). One honest `total` count and
         *     a real last-scan time/status — never a silent 200-row cap or hardcoded refresh.
         *     `list_q` / `text_q` (FR-JB-13) filter server-side *before* pagination — the
         *     feed is paginated, so a client-side filter over loaded pages would silently
         *     miss matches on unloaded pages.
         */
        get: operations["board_api_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Job
         * @description Add-by-URL step 1 (US-JB-07): fetch the pasted URL and extract editable
         *     fields — best-effort, not persisted. 20 s fetch, no auto-retry (§17b). The
         *     blocking probe runs off the event loop.
         *
         *     Two DB short-circuits before the network probe: a **tombstoned** URL fails
         *     fast with the honest 409 (re-add is impossible); an **existing** URL (active
         *     or Trashed) returns its stored fields — we "fetch it back" from our own copy
         *     rather than re-scrape.
         */
        post: operations["preview_job_api_jobs_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Job
         * @description App-side job state (Trash — US-JB-11; Expired — FR-SYS-03). Moving into/out
         *     of `removed` routes through `set_trash_state` (7-day TTL clock); un-expiring an
         *     `expired` job routes through `unexpire` (resets the 14-day timer).
         */
        patch: operations["update_job_api_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/tombstone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tombstone Job
         * @description Delete forever from Trash (US-JB-11): write a `Tombstone` for the job's
         *     canonical URL, then hard-delete the row. A tombstone is final — a future
         *     scan or Add-by-URL can never re-surface it (FR-SYS-04).
         */
        post: operations["tombstone_job_api_jobs__job_id__tombstone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/trash/empty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Empty Trash
         * @description Empty Trash (US-JB-11 / FR-SYS-04): tombstone every Trashed job's URL and
         *     hard-delete the rows immediately, bypassing the 7-day TTL.
         */
        post: operations["empty_trash_api_jobs_trash_empty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        /** Upsert Profile */
        post: operations["upsert_profile_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Application Profile
         * @description Manually (re-)extract the application profile from the current master
         *     (the Settings "Re-extract" button — FR-APP-01).
         */
        post: operations["extract_application_profile_api_profile_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/application-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Application Profile
         * @description Persist manual edits to the application profile (Settings editor).
         *     The payload replaces the stored record verbatim, stamped `source: edited`
         *     — deterministic user edits always win over extraction.
         */
        patch: operations["patch_application_profile_api_profile_application_profile_patch"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /**
         * Replace Settings
         * @description PUT is an alias of POST for the settings map (idempotent update).
         */
        put: operations["replace_settings_api_settings_put"];
        /** Update Settings */
        post: operations["update_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Packet
         * @description Manual/regenerate packet build (US-TL-02) — supersedes prior artifacts.
         */
        post: operations["generate_packet_api_applications__application_id__packet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/artifacts/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Artifact
         * @description Persist an edited variant + the Approve-and-Save flip (US-RES-02 / FR-RES-02).
         *
         *     Targets the head (non-superseded) artifact of `kind` for this application.
         *     `markdown` overwrites the text (edits apply only to this variant — the master
         *     is untouched); `approved` stamps/clears `approved_at` (the `ready ⇄ approved`
         *     flip). Per-artifact, so the resume and cover letter are approved separately.
         */
        patch: operations["patch_artifact_api_applications__application_id__artifacts__kind__patch"];
        trace?: never;
    };
    "/api/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_api_applications__application_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Application
         * @description Remove a card (unsave / return-to-board — US-JB / US-TR-07).
         */
        delete: operations["delete_application_api_applications__application_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Application
         * @description Move/annotate/archive a card. Column moves, notes edits, and
         *     archive/unarchive each write an `ApplicationEvent` (only on real change —
         *     a no-op PATCH records nothing). `intent` is the §5.1 exclusive value:
         *     setting it replaces the previous one wholesale.
         */
        patch: operations["update_application_api_applications__application_id__patch"];
        trace?: never;
    };
    "/api/applications/{application_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Application Activity
         * @description Real Activity log for one application (US-TR-03 / FR-TR-03) — composed from
         *     the operations ledger + card events, never synthesized client-side. Records:
         *     added-to-tracker, score, tailor/cover generation, column moves, notes edits,
         *     archive/unarchive. (Apply + outreach entries return with their commits.)
         */
        get: operations["application_activity_api_applications__application_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schedules
         * @description The recurring-enqueue rules (scan / score_new). Seeded disabled (§7 seed).
         */
        get: operations["list_schedules_api_schedules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Schedule
         * @description Enable/disable a schedule or change its cadence. Enabling a seeded-
         *     disabled schedule makes it due on the next tick (next_due_at → now).
         */
        patch: operations["update_schedule_api_schedules__schedule_id__patch"];
        trace?: never;
    };
    "/api/schedules/{schedule_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Schedule
         * @description Run a schedule now, regardless of enabled/due — the explicit user trigger
         *     (score_new fans out to a `score` op per unscored job; scan enqueues one scan).
         *     Idempotent for score_new: the planner skips already-scored + pending jobs.
         */
        post: operations["run_schedule_api_schedules__schedule_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Operation
         * @description Enqueue an operation; return its id immediately (architecture §4.2).
         */
        post: operations["create_operation_api_operations__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Operation
         * @description Re-enqueue a failed operation with its original input snapshot — the Logs
         *     "App restarted while generating — retry?" affordance (US-LOG-01). Same kind,
         *     same inputs; a fresh operation id (the failed row stays as the audit record).
         *     `apply`/`linkedin_login` are excluded (interactive, non-generic paths).
         */
        post: operations["retry_operation_api_operations__operation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Operations
         * @description Recent operations — the ledger the Logs/Analytics surfaces read (§10).
         */
        get: operations["list_operations_api_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cost/totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost Totals
         * @description All-time cost totals for the Analytics cost tiles (FR-SET-07 / US-LOG-01 #2).
         *
         *     Live-ledger sum + the persisted pruned-ops aggregate, so the tiles show
         *     lifetime spend that survives the ~250-op ledger retention — not just the
         *     retained window (NFR-COST-02: the running spend total stays honest as an
         *     install ages).
         */
        get: operations["cost_totals_api_cost_totals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_api_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Engine */
        post: operations["verify_engine_api_engines_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engines */
        get: operations["list_engines_api_engines_get"];
        put?: never;
        /** Save Engine */
        post: operations["save_engine_api_engines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Engine */
        delete: operations["delete_engine_api_engines__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEntryDTO
         * @description One real event on an application's Activity tab (US-TR-03 / FR-TR-03),
         *     composed from the ledger — never synthesized client-side.
         */
        ActivityEntryDTO: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** State */
            state?: string | null;
            /** At */
            at?: string | null;
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Job Id */
            job_id: string;
            /**
             * Column
             * @default saved
             */
            column: string;
            /** Priority */
            priority?: string | null;
            /**
             * Notes Markdown
             * @default
             */
            notes_markdown: string;
            /** Generate Resume */
            generate_resume?: boolean | null;
            /** Generate Cover */
            generate_cover?: boolean | null;
            /**
             * Guidance
             * @default
             */
            guidance: string;
        };
        /** ApplicationDTO */
        ApplicationDTO: {
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            job?: components["schemas"]["JobDTO"] | null;
            /** Column */
            column: string;
            /** Priority */
            priority: string;
            /**
             * Intent
             * @default none
             */
            intent: string;
            /** Notes Markdown */
            notes_markdown: string;
            /** Applied Via */
            applied_via: string | null;
            /** Preview Screenshot Path */
            preview_screenshot_path: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            /**
             * Last Touched At
             * Format: date-time
             */
            last_touched_at: string;
            /** Packetstate */
            packetState: string;
            /**
             * Packetresumestate
             * @default none
             */
            packetResumeState: string;
            /**
             * Packetcoverletterstate
             * @default none
             */
            packetCoverLetterState: string;
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactDTO"][];
        };
        /** ApplicationUpdate */
        ApplicationUpdate: {
            /** Column */
            column?: string | null;
            /** Priority */
            priority?: string | null;
            /** Intent */
            intent?: ("none" | "referral" | "apply") | null;
            /** Notes Markdown */
            notes_markdown?: string | null;
            /** Applied Via */
            applied_via?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** ArtifactDTO */
        ArtifactDTO: {
            /** Id */
            id: string;
            /** Application Id */
            application_id: string;
            /** Kind */
            kind: string;
            /** Markdown */
            markdown: string;
            /** Notes */
            notes: unknown[];
            /** Profile Version */
            profile_version: number;
            /** Guidance Used */
            guidance_used: string | null;
            /** Operation Id */
            operation_id: string | null;
            /** Operation State */
            operation_state?: string | null;
            /** Superseded By */
            superseded_by: string | null;
            /** Approved At */
            approved_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ArtifactPatch
         * @description Persist an edited variant + the Approve-and-Save flip (US-RES-02 / FR-RES-02).
         *
         *     `markdown` overwrites the head artifact's text; `approved=True` stamps
         *     `approved_at` (flip `ready → approved`), `approved=False` clears it.
         */
        ArtifactPatch: {
            /** Markdown */
            markdown?: string | null;
            /** Approved */
            approved?: boolean | null;
        };
        /**
         * BoardPageDTO
         * @description One page of the Job Board feed (FR-JB-02) plus the header meta the board
         *     needs (FR-JB-10): a real last-scan time + scrape status so the empty state is
         *     always explained, never a silent blank. Saved jobs are excluded server-side.
         */
        BoardPageDTO: {
            /** Jobs */
            jobs: components["schemas"]["JobDTO"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Scanstatus */
            scanStatus: string;
            /** Lastscanat */
            lastScanAt?: string | null;
            /** Scanerror */
            scanError?: string | null;
        };
        /**
         * CostTotalsDTO
         * @description All-time cost totals for the Analytics cost tiles (FR-SET-07 / US-LOG-01 #2).
         *
         *     Live-ledger sum + the pruned-ops aggregate, so the figures are lifetime totals
         *     that survive ledger retention — not just the retained ~250 ops. `by_kind` maps
         *     each operation kind to its all-time usd spend.
         */
        CostTotalsDTO: {
            /** Usd */
            usd: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Operations */
            operations: number;
            /** Failed */
            failed: number;
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
        };
        /**
         * EngineSettingDTO
         * @description Engine config sans secret — `has_key` reports presence, `key_hint` is a
         *     masked display fragment (e.g. `sk-…abc4`), never the key itself.
         */
        EngineSettingDTO: {
            /** Id */
            id: string;
            /** Engine */
            engine: string;
            /** Base Url */
            base_url: string | null;
            /** Default Model */
            default_model: string | null;
            /** Enabled */
            enabled: boolean;
            /** Has Key */
            has_key: boolean;
            /** Key Hint */
            key_hint: string | null;
        };
        /**
         * EngineSettingUpsert
         * @description Save/replace a provider's config. Omitting `key` leaves any existing
         *     sealed key intact; sending `key` re-seals. The key never round-trips back.
         */
        EngineSettingUpsert: {
            /** Provider */
            provider: string;
            /** Key */
            key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * EngineVerifyRequest
         * @description A provider-appropriate verify probe (FR-SET-06). `key` is sent for a
         *     verify-only check and is never persisted by this call.
         */
        EngineVerifyRequest: {
            /** Provider */
            provider: string;
            /** Key */
            key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model?: string | null;
        };
        /** EngineVerifyResult */
        EngineVerifyResult: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
            /** Provider */
            provider: string;
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "not_found" | "not_logged_in" | "error";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreate
         * @description Add-by-URL (US-JB-07) + programmatic ingest.
         */
        JobCreate: {
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Posted At */
            posted_at?: string | null;
            /** Salary */
            salary?: string | null;
            /**
             * Source Adapter
             * @default paste-url
             */
            source_adapter: string;
        };
        /** JobDTO */
        JobDTO: {
            /** Id */
            id: string;
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Posted At */
            posted_at: string | null;
            /** Salary */
            salary: string | null;
            /** Source Adapter */
            source_adapter: string;
            /** Trust Score */
            trust_score: number;
            /** Trust Flags */
            trust_flags: string[];
            /** Feed State */
            feed_state: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /**
             * Workstyle
             * @default
             */
            workStyle: string;
            score?: components["schemas"]["JobScoreDTO"] | null;
            /**
             * Scorestatus
             * @default pending
             */
            scoreStatus: string;
        };
        /**
         * JobPreviewDTO
         * @description The editable review payload the Add-by-URL modal shows before submit.
         *
         *     Best-effort — a known ATS URL comes back fully structured; a generic page
         *     fills what it can and the user edits the rest.
         */
        JobPreviewDTO: {
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Posted At */
            posted_at: string | null;
            /** Salary */
            salary: string | null;
            /** Source Adapter */
            source_adapter: string;
        };
        /**
         * JobPreviewRequest
         * @description Add-by-URL step 1 (US-JB-07): fetch a pasted URL, extract fields, no persist.
         */
        JobPreviewRequest: {
            /** Url */
            url: string;
        };
        /**
         * JobScoreDTO
         * @description The cached fit score for the current master version (FR-JB-01 sort).
         */
        JobScoreDTO: {
            /** Score 0 100 */
            score_0_100: number;
            /** Reasons */
            reasons: unknown[];
            /** Breakdown Md */
            breakdown_md: string;
        };
        /**
         * JobUpdate
         * @description App-side job state — Trash (US-JB-11): `feed_state` active/removed.
         */
        JobUpdate: {
            /** Feed State */
            feed_state?: string | null;
        };
        /** OperationAccepted */
        OperationAccepted: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
        };
        /** OperationDTO */
        OperationDTO: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: unknown;
            };
            /** Result Ref */
            result_ref: {
                [key: string]: unknown;
            } | null;
            /** Usage */
            usage: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /** Engine */
            engine: string | null;
            /** Model */
            model: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * PacketRequest
         * @description Manual/regenerate packet build for an existing application (US-TL-02).
         */
        PacketRequest: {
            /**
             * Resume
             * @default true
             */
            resume: boolean;
            /**
             * Cover
             * @default true
             */
            cover: boolean;
            /**
             * Guidance
             * @default
             */
            guidance: string;
        };
        /** PreferencesDTO */
        PreferencesDTO: {
            /** Role Aliases */
            role_aliases: unknown[];
            /** Locations */
            locations: unknown[];
            /** Freshness Days */
            freshness_days: number;
            /** Hard Excludes */
            hard_excludes: {
                [key: string]: unknown;
            };
            /** Hard Requires */
            hard_requires: {
                [key: string]: unknown;
            };
            /** Soft Preferences */
            soft_preferences: {
                [key: string]: unknown;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
            /** Portals Config */
            portals_config: {
                [key: string]: unknown;
            };
            /** Voyager Risk Marker On */
            voyager_risk_marker_on: boolean;
            /** Engine Routing */
            engine_routing: {
                [key: string]: unknown;
            };
            /** Ui State */
            ui_state: {
                [key: string]: unknown;
            };
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Role Aliases */
            role_aliases?: unknown[] | null;
            /** Locations */
            locations?: unknown[] | null;
            /** Freshness Days */
            freshness_days?: number | null;
            /** Hard Excludes */
            hard_excludes?: {
                [key: string]: unknown;
            } | null;
            /** Hard Requires */
            hard_requires?: {
                [key: string]: unknown;
            } | null;
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            } | null;
            /** Thresholds */
            thresholds?: {
                [key: string]: unknown;
            } | null;
            /** Portals Config */
            portals_config?: {
                [key: string]: unknown;
            } | null;
            /** Voyager Risk Marker On */
            voyager_risk_marker_on?: boolean | null;
            /** Engine Routing */
            engine_routing?: {
                [key: string]: unknown;
            } | null;
            /** Ui State */
            ui_state?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProfileDTO */
        ProfileDTO: {
            /** Id */
            id: string;
            /** Resume Markdown */
            resume_markdown: string;
            /** Version */
            version: number;
            /** Application Profile */
            application_profile?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileUpsert */
        ProfileUpsert: {
            /** Resume Markdown */
            resume_markdown: string;
        };
        /** ScheduleDTO */
        ScheduleDTO: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Interval Minutes */
            interval_minutes: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Next Due At
             * Format: date-time
             */
            next_due_at: string;
            /** Last Enqueued Operation Id */
            last_enqueued_operation_id: string | null;
        };
        /**
         * ScheduleRunResult
         * @description The `POST /api/schedules/{id}/run` response: the schedule + enqueued ops.
         */
        ScheduleRunResult: {
            schedule: components["schemas"]["ScheduleDTO"];
            /** Enqueued */
            enqueued: string[];
        };
        /**
         * ScheduleUpdate
         * @description Enable/disable a schedule or change its cadence.
         */
        ScheduleUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Interval Minutes */
            interval_minutes?: number | null;
        };
        /** SettingsDTO */
        SettingsDTO: {
            preferences: components["schemas"]["PreferencesDTO"];
            /** Engines */
            engines: components["schemas"]["EngineSettingDTO"][];
        };
        /**
         * TombstoneResultDTO
         * @description Result of a permanent-discard action (Empty Trash / Delete forever /
         *     TTL eviction — US-JB-11 / FR-SYS-04): how many URLs were tombstoned.
         */
        TombstoneResultDTO: {
            /** Tombstoned */
            tombstoned: number;
            /** Canonical Urls */
            canonical_urls: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    shutdown_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                feed_state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_api_board_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                list_q?: string;
                text_q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_job_api_jobs_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPreviewDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_api_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tombstone_job_api_jobs__job_id__tombstone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TombstoneResultDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    empty_trash_api_jobs_trash_empty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TombstoneResultDTO"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"] | null;
                };
            };
        };
    };
    upsert_profile_api_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_application_profile_api_profile_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
        };
    };
    patch_application_profile_api_profile_application_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
        };
    };
    replace_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_packet_api_applications__application_id__packet_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PacketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_artifact_api_applications__application_id__artifacts__kind__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_activity_api_applications__application_id__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEntryDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_api_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleDTO"][];
                };
            };
        };
    };
    update_schedule_api_schedules__schedule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_schedule_api_schedules__schedule_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_operation_api_operations__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_operation_api_operations__operation_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operations_api_operations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_totals_api_cost_totals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostTotalsDTO"];
                };
            };
        };
    };
    get_operation_api_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_engine_api_engines_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngineVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineVerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engines_api_engines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettingDTO"][];
                };
            };
        };
    };
    save_engine_api_engines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngineSettingUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettingDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_engine_api_engines__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
