/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. Open (no token) — the shell polls this (§4.4 step 2).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description SSE stream of typed `{type, payload}` envelopes: operation events from
         *     the runner, with heartbeats on idle.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shutdown
         * @description Respond 200, then exit cleanly (the drain runs in the app lifespan).
         */
        post: operations["shutdown_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        /** Upsert Profile */
        post: operations["upsert_profile_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Application Profile
         * @description Manually (re-)extract the application profile from the current master
         *     (the Settings "Re-extract" button — FR-APP-01).
         */
        post: operations["extract_application_profile_api_profile_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/application-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Application Profile
         * @description Persist manual edits to the application profile (Settings editor).
         *     The payload replaces the stored record verbatim, stamped `source: edited`
         *     — deterministic user edits always win over extraction.
         */
        patch: operations["patch_application_profile_api_profile_application_profile_patch"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /**
         * Replace Settings
         * @description PUT is an alias of POST for the settings map (idempotent update).
         */
        put: operations["replace_settings_api_settings_put"];
        /** Update Settings */
        post: operations["update_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Operation
         * @description Enqueue an operation; return its id immediately (architecture §4.2).
         */
        post: operations["create_operation_api_operations__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Operation
         * @description Re-enqueue a failed operation with its original input snapshot — the Logs
         *     "App restarted while generating — retry?" affordance (US-LOG-01). Same kind,
         *     same inputs; a fresh operation id (the failed row stays as the audit record).
         *     `apply`/`linkedin_login` are excluded (interactive, non-generic paths).
         */
        post: operations["retry_operation_api_operations__operation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Operations
         * @description Recent operations — the ledger the Logs/Analytics surfaces read (§10).
         */
        get: operations["list_operations_api_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cost/totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost Totals
         * @description All-time cost totals for the Analytics cost tiles (FR-SET-07 / US-LOG-01 #2).
         *
         *     Live-ledger sum + the persisted pruned-ops aggregate, so the tiles show
         *     lifetime spend that survives the ~250-op ledger retention — not just the
         *     retained window (NFR-COST-02: the running spend total stays honest as an
         *     install ages).
         */
        get: operations["cost_totals_api_cost_totals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_api_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Engine */
        post: operations["verify_engine_api_engines_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engines */
        get: operations["list_engines_api_engines_get"];
        put?: never;
        /** Save Engine */
        post: operations["save_engine_api_engines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engines/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Engine */
        delete: operations["delete_engine_api_engines__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CostTotalsDTO
         * @description All-time cost totals for the Analytics cost tiles (FR-SET-07 / US-LOG-01 #2).
         *
         *     Live-ledger sum + the pruned-ops aggregate, so the figures are lifetime totals
         *     that survive ledger retention — not just the retained ~250 ops. `by_kind` maps
         *     each operation kind to its all-time usd spend.
         */
        CostTotalsDTO: {
            /** Usd */
            usd: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Operations */
            operations: number;
            /** Failed */
            failed: number;
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
        };
        /**
         * EngineSettingDTO
         * @description Engine config sans secret — `has_key` reports presence, `key_hint` is a
         *     masked display fragment (e.g. `sk-…abc4`), never the key itself.
         */
        EngineSettingDTO: {
            /** Id */
            id: string;
            /** Engine */
            engine: string;
            /** Base Url */
            base_url: string | null;
            /** Default Model */
            default_model: string | null;
            /** Enabled */
            enabled: boolean;
            /** Has Key */
            has_key: boolean;
            /** Key Hint */
            key_hint: string | null;
        };
        /**
         * EngineSettingUpsert
         * @description Save/replace a provider's config. Omitting `key` leaves any existing
         *     sealed key intact; sending `key` re-seals. The key never round-trips back.
         */
        EngineSettingUpsert: {
            /** Provider */
            provider: string;
            /** Key */
            key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * EngineVerifyRequest
         * @description A provider-appropriate verify probe (FR-SET-06). `key` is sent for a
         *     verify-only check and is never persisted by this call.
         */
        EngineVerifyRequest: {
            /** Provider */
            provider: string;
            /** Key */
            key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model?: string | null;
        };
        /** EngineVerifyResult */
        EngineVerifyResult: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
            /** Provider */
            provider: string;
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "not_found" | "not_logged_in" | "error";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OperationAccepted */
        OperationAccepted: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
        };
        /** OperationDTO */
        OperationDTO: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: unknown;
            };
            /** Result Ref */
            result_ref: {
                [key: string]: unknown;
            } | null;
            /** Usage */
            usage: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /** Engine */
            engine: string | null;
            /** Model */
            model: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** PreferencesDTO */
        PreferencesDTO: {
            /** Role Aliases */
            role_aliases: unknown[];
            /** Locations */
            locations: unknown[];
            /** Freshness Days */
            freshness_days: number;
            /** Hard Excludes */
            hard_excludes: {
                [key: string]: unknown;
            };
            /** Hard Requires */
            hard_requires: {
                [key: string]: unknown;
            };
            /** Soft Preferences */
            soft_preferences: {
                [key: string]: unknown;
            };
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
            /** Portals Config */
            portals_config: {
                [key: string]: unknown;
            };
            /** Voyager Risk Marker On */
            voyager_risk_marker_on: boolean;
            /** Engine Routing */
            engine_routing: {
                [key: string]: unknown;
            };
            /** Ui State */
            ui_state: {
                [key: string]: unknown;
            };
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Role Aliases */
            role_aliases?: unknown[] | null;
            /** Locations */
            locations?: unknown[] | null;
            /** Freshness Days */
            freshness_days?: number | null;
            /** Hard Excludes */
            hard_excludes?: {
                [key: string]: unknown;
            } | null;
            /** Hard Requires */
            hard_requires?: {
                [key: string]: unknown;
            } | null;
            /** Soft Preferences */
            soft_preferences?: {
                [key: string]: unknown;
            } | null;
            /** Thresholds */
            thresholds?: {
                [key: string]: unknown;
            } | null;
            /** Portals Config */
            portals_config?: {
                [key: string]: unknown;
            } | null;
            /** Voyager Risk Marker On */
            voyager_risk_marker_on?: boolean | null;
            /** Engine Routing */
            engine_routing?: {
                [key: string]: unknown;
            } | null;
            /** Ui State */
            ui_state?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProfileDTO */
        ProfileDTO: {
            /** Id */
            id: string;
            /** Resume Markdown */
            resume_markdown: string;
            /** Version */
            version: number;
            /** Application Profile */
            application_profile?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProfileUpsert */
        ProfileUpsert: {
            /** Resume Markdown */
            resume_markdown: string;
        };
        /** SettingsDTO */
        SettingsDTO: {
            preferences: components["schemas"]["PreferencesDTO"];
            /** Engines */
            engines: components["schemas"]["EngineSettingDTO"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    shutdown_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"] | null;
                };
            };
        };
    };
    upsert_profile_api_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_application_profile_api_profile_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
        };
    };
    patch_application_profile_api_profile_application_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
        };
    };
    replace_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_operation_api_operations__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_operation_api_operations__operation_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operations_api_operations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_totals_api_cost_totals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostTotalsDTO"];
                };
            };
        };
    };
    get_operation_api_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_engine_api_engines_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngineVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineVerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engines_api_engines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettingDTO"][];
                };
            };
        };
    };
    save_engine_api_engines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngineSettingUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineSettingDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_engine_api_engines__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
