"""The boring-schema pass: 4 changes the maintainer settled on 2026-09-01.

1. `job_scores` collapses into 6 columns on `jobs`. The 3-part key carried a
   `profile_version` dimension that never distinguished anything (1,238 rows,
   614 distinct `(job_id, scorer_impl)` pairs, 0 pairs holding 2 payloads) and
   made 2 selection defects possible. Display becomes `llm_score ?? keyword_score`,
   a rule with no ranking in it. `score_attempts` / `score_last_error` gain their
   `llm_` prefix, which is the scope they always had.
2. `applications.job_id` becomes unique. One tracker card per role; the reads
   already assumed it and nothing enforced it.
3. `documents` + `application_documents` merge. The many-to-many was never
   exercised and is what made the detach path leak the row and the blob.
4. `contact_job_assocs` becomes `referral_candidates`. A row means "this person
   is a referral candidate for this role"; `assoc` named the mechanism.

Every collapse is lossless on the maintainer's install, verified before writing:
no `(job_id, scorer_impl)` pair holds 2 different payloads, no job carries 2
applications, and all 3 documents are linked exactly once.

Revision ID: d2f7a91b8c46
Revises: b6e2f04a7d13
Create Date: 2026-09-01
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "d2f7a91b8c46"
down_revision = "b6e2f04a7d13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()

    # -- 1. job_scores → 6 columns on jobs ---------------------------------
    # Stash the surviving row per (job, scorer) BEFORE dropping the table, so
    # the `jobs` batch-recreate below never runs with an inbound foreign key
    # pointing at the table it is rebuilding.
    op.execute(
        """
        CREATE TABLE _score_snapshot AS
        SELECT job_id, scorer_impl, score_0_100, reasons, breakdown_md
        FROM (
            SELECT job_id, scorer_impl, score_0_100, reasons, breakdown_md,
                   ROW_NUMBER() OVER (
                       PARTITION BY job_id, scorer_impl
                       ORDER BY profile_version DESC
                   ) AS rn
            FROM job_scores
        )
        WHERE rn = 1
        """
    )
    op.drop_table("job_scores")

    with op.batch_alter_table("jobs") as batch:
        batch.add_column(sa.Column("llm_score", sa.Integer(), nullable=True))
        batch.add_column(
            sa.Column("llm_reasons", sa.JSON(), nullable=False, server_default="[]")
        )
        batch.add_column(
            sa.Column("llm_breakdown_md", sa.Text(), nullable=False, server_default="")
        )
        batch.add_column(sa.Column("keyword_score", sa.Integer(), nullable=True))
        batch.add_column(
            sa.Column("keyword_reasons", sa.JSON(), nullable=False, server_default="[]")
        )
        batch.add_column(
            sa.Column(
                "keyword_breakdown_md", sa.Text(), nullable=False, server_default=""
            )
        )
        batch.alter_column("score_attempts", new_column_name="llm_score_attempts")
        batch.alter_column("score_last_error", new_column_name="llm_score_last_error")

    # The batch recreate carries the old index name over an autogenerated one;
    # drop and recreate it on the renamed column so the schema reads honestly.
    op.drop_index("ix_jobs_feedstate_attempts", table_name="jobs")
    op.create_index(
        "ix_jobs_feedstate_attempts", "jobs", ["feed_state", "llm_score_attempts"]
    )

    for impl, prefix in (("scorer-llm", "llm"), ("scorer-deterministic", "keyword")):
        bind.execute(
            sa.text(
                f"""
                UPDATE jobs SET
                    {prefix}_score = (
                        SELECT score_0_100 FROM _score_snapshot s
                        WHERE s.job_id = jobs.id AND s.scorer_impl = :impl),
                    {prefix}_reasons = COALESCE((
                        SELECT reasons FROM _score_snapshot s
                        WHERE s.job_id = jobs.id AND s.scorer_impl = :impl), '[]'),
                    {prefix}_breakdown_md = COALESCE((
                        SELECT breakdown_md FROM _score_snapshot s
                        WHERE s.job_id = jobs.id AND s.scorer_impl = :impl), '')
                WHERE EXISTS (
                    SELECT 1 FROM _score_snapshot s
                    WHERE s.job_id = jobs.id AND s.scorer_impl = :impl)
                """  # noqa: S608  prefix is a literal from the loop above
            ),
            {"impl": impl},
        )
    op.drop_table("_score_snapshot")

    # -- 2. one tracker card per job ---------------------------------------
    # Any pre-existing duplicate keeps its OLDEST card: that is the one whose
    # id every artifact, event, document link and apply run already points at.
    op.execute(
        """
        DELETE FROM applications WHERE id NOT IN (
            SELECT MIN(id) FROM applications GROUP BY job_id
        )
        """
    )
    # A unique INDEX, not a table-level constraint: it enforces identically and
    # costs no recreate of a table 4 others point at. It is also the index
    # `job_id` never had.
    op.create_index("uq_applications_job", "applications", ["job_id"], unique=True)

    # -- 3. documents + application_documents → documents -------------------
    op.create_table(
        "documents_merged",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("application_id", sa.String(), nullable=False),
        sa.Column("doc_type", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("mime_type", sa.String(), nullable=False, server_default=""),
        sa.Column("original_filename", sa.String(), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "doc_type", name="uq_documents_card_type"),
    )
    op.execute(
        """
        INSERT INTO documents_merged
            (id, application_id, doc_type, sha256, byte_size, mime_type,
             original_filename, created_at)
        SELECT ad.id, ad.application_id, ad.kind, d.sha256, d.byte_size,
               d.mime_type, d.original_filename, ad.created_at
        FROM application_documents ad JOIN documents d ON d.id = ad.document_id
        """
    )
    op.drop_table("application_documents")
    op.drop_table("documents")
    op.rename_table("documents_merged", "documents")
    op.create_index("ix_documents_application", "documents", ["application_id"])

    # -- 4. contact_job_assocs → referral_candidates ------------------------
    # Created fresh rather than renamed so the constraint and index names come
    # out matching the table, instead of SQLite carrying `uq_contactjob` along.
    op.create_table(
        "referral_candidates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("contact_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("audience_tag", sa.String(), nullable=False, server_default="other"),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("selected", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"]),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_id", "job_id", name="uq_referral_candidate"),
    )
    op.execute(
        """
        INSERT INTO referral_candidates
            (id, contact_id, job_id, audience_tag, status, selected, added_at)
        SELECT id, contact_id, job_id, audience_tag, status, selected, added_at
        FROM contact_job_assocs
        """
    )
    op.drop_table("contact_job_assocs")
    op.create_index("ix_referral_candidate_job", "referral_candidates", ["job_id"])


def downgrade() -> None:
    op.create_table(
        "contact_job_assocs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("contact_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("audience_tag", sa.String(), nullable=False, server_default="other"),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("selected", sa.Boolean(), nullable=False, server_default="0"),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"]),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_id", "job_id", name="uq_contactjob"),
    )
    op.execute(
        """
        INSERT INTO contact_job_assocs
        SELECT id, contact_id, job_id, audience_tag, status, selected, added_at
        FROM referral_candidates
        """
    )
    op.drop_table("referral_candidates")
    op.create_index("ix_contactjob_job", "contact_job_assocs", ["job_id"])

    op.create_table(
        "documents_registry",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("mime_type", sa.String(), nullable=False, server_default=""),
        sa.Column("original_filename", sa.String(), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_documents_sha256"),
    )
    op.create_table(
        "application_documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("application_id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"]),
        sa.ForeignKeyConstraint(["document_id"], ["documents_registry.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "kind", name="uq_appdoc_kind"),
    )
    # One registry row per distinct blob, then a link per merged row.
    op.execute(
        """
        INSERT INTO documents_registry
            (id, sha256, byte_size, mime_type, original_filename, created_at)
        SELECT MIN(id), sha256, MIN(byte_size), MIN(mime_type),
               MIN(original_filename), MIN(created_at)
        FROM documents GROUP BY sha256
        """
    )
    op.execute(
        """
        INSERT INTO application_documents
            (id, application_id, document_id, kind, created_at)
        SELECT d.id, d.application_id,
               (SELECT r.id FROM documents_registry r WHERE r.sha256 = d.sha256),
               d.doc_type, d.created_at
        FROM documents d
        """
    )
    op.drop_table("documents")
    op.rename_table("documents_registry", "documents")
    op.create_index("ix_appdoc_application", "application_documents", ["application_id"])

    op.drop_index("uq_applications_job", table_name="applications")

    op.create_table(
        "job_scores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("score_0_100", sa.Integer(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("breakdown_md", sa.Text(), nullable=False, server_default=""),
        sa.Column("scorer_impl", sa.String(), nullable=False, server_default="scorer-llm"),
        sa.Column("operation_id", sa.String(), nullable=True),
        sa.Column("scored_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"]),
        sa.ForeignKeyConstraint(["operation_id"], ["operations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id", "profile_version", "scorer_impl", name="uq_jobscore_cachekey"
        ),
    )
    # Version 1 for every restored row: the real versions were collapsed away on
    # the way up and no reader ever looked at them.
    for impl, prefix in (("scorer-llm", "llm"), ("scorer-deterministic", "keyword")):
        op.execute(
            f"""
            INSERT INTO job_scores
                (id, job_id, profile_version, score_0_100, reasons, breakdown_md,
                 scorer_impl, operation_id, scored_at)
            SELECT lower(hex(randomblob(16))), id, 1, {prefix}_score,
                   {prefix}_reasons, {prefix}_breakdown_md, '{impl}', NULL,
                   CURRENT_TIMESTAMP
            FROM jobs WHERE {prefix}_score IS NOT NULL
            """  # noqa: S608  both interpolations are literals from the loop
        )

    op.drop_index("ix_jobs_feedstate_attempts", table_name="jobs")
    with op.batch_alter_table("jobs") as batch:
        batch.alter_column("llm_score_attempts", new_column_name="score_attempts")
        batch.alter_column("llm_score_last_error", new_column_name="score_last_error")
        batch.drop_column("keyword_breakdown_md")
        batch.drop_column("keyword_reasons")
        batch.drop_column("keyword_score")
        batch.drop_column("llm_breakdown_md")
        batch.drop_column("llm_reasons")
        batch.drop_column("llm_score")
    op.create_index(
        "ix_jobs_feedstate_attempts", "jobs", ["feed_state", "score_attempts"]
    )
